---
name: 01 Continuous Integration
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      bicep_cli_version:
        description: 'Bicep CLI Version'
        required: true
        default: 'latest'
        type: string

jobs:
  validate:
    name: Validate Bicep
    runs-on:
      ${environments[keys(environments)[0]].runner_name}
    steps:
      - name: Validate Bicep
        uses: ${organization_name}/${repository_name_templates}/.github/actions/validate@main
        with:
          root_module_folder_relative_path: '${root_module_folder_relative_path}'
          deployments_json: '${jsonencode(deployments)}'

%{ for environment in environments ~}
  ${environment.name}_validate:
    uses: ${organization_name}/${repository_name_templates}/${ci_template_path}@main
    name: ${environment.display_name}
    needs: validate
    permissions:
      id-token: write
      contents: read
    with:
      root_module_folder_relative_path: '${root_module_folder_relative_path}'
      name: ${environment.name}
      display_name: ${environment.display_name}
      runner_name: ${environment.runner_name}
      environment_name_read: ${environment.environment_name_read}
      environment_name_write: ${environment.environment_name_write}
      dependent_environment: ${environment.dependent_environment}
      backend_azure_storage_account_container_name: ${environment.backend_azure_storage_account_container_name}
      deployments_json: '${jsonencode(deployments)}'

%{ endfor ~}
