---
name: Run Bicep Validate
description: Run Bicep Validate
inputs:
  root_module_folder_relative_path:
    description: 'Root Module Folder Relative Path'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Bicep Build (Validate)
      shell: pwsh
      run: |
        $deploymentsJson = $env:BICEP_DEPLOYMENTS
        if([string]::IsNullOrEmpty($deploymentsJson)) {
          az bicep build --file "${{inputs.root_module_folder_relative_path}}/main.bicep"
        } else {
          $deployments = ConvertFrom-Json $deploymentsJson
          foreach($deployment in $deployments) {
            Write-Host "Validating: $($deployment.template_file)"
            az bicep build --file "${{inputs.root_module_folder_relative_path}}/$($deployment.template_file)"
          }
        }
